/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Mockup.Ventanas;

import Gestion.GallinaGestion;
import Gestion.ProduccionGestion;
import Gestion.VariablesGlobales;
import Modelo.Gallina;
import Modelo.Produccion;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author angie
 */
public class VistaGestionProduccion extends javax.swing.JFrame {

    private ProduccionGestion gestion = new ProduccionGestion();
    private GallinaGestion gestionGallina = new GallinaGestion();

    public VistaGestionProduccion() {
        initComponents();
    }

    public void Buscar() {
        String codigo = this.txtCodigo.getText();
        if (codigo.isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo de codigo es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Gallina gallina = gestionGallina.buscar(codigo);
            if (gallina != null) {
                this.txtCantidadHuevos.setEnabled(true);
                this.txtCodigo.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "La Gallina no existe", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    public void Guardar() {
        try {
            String codigo = this.txtCodigo.getText();
            String cantidad = this.txtCantidadHuevos.getText();
            if (codigo.isBlank()) {
                JOptionPane.showMessageDialog(null, "El campo de codigo es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (cantidad.isBlank()) {
                JOptionPane.showMessageDialog(null, "El campo de cantidad es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                Gallina gallina = gestionGallina.buscar(codigo);
                if (gallina == null) {
                    JOptionPane.showMessageDialog(null, "La gallina no existe", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    Produccion produccion = new Produccion();
                    int cantidadEntero = Integer.parseInt(cantidad);
                    LocalDate fecha = LocalDate.now();
                    produccion.setCantidadHuevos(cantidadEntero);
                    produccion.setFecha(fecha);

                    String respuestaGuardado = gestion.guardar(produccion, codigo);
                    if (respuestaGuardado.equals("OK")) {
                        JOptionPane.showMessageDialog(null, "Guardado exitosamente", "Exitoso", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, respuestaGuardado, "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        } catch (Exception e) {
            //ACA PASO UN ERROR EN CONVERSIONES O CUALQUIER OTRA COSA
            JOptionPane.showMessageDialog(null, "Ocurrio un error al validar la información, porfavor verifique los datos", "Error", JOptionPane.ERROR_MESSAGE);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCodigo = new javax.swing.JTextField();
        tituloGranja = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCantidadHuevos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 110, -1));

        tituloGranja.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tituloGranja.setText("Produccion");
        getContentPane().add(tituloGranja, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrar.setText("Guardar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 130, 30));

        Volver.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 130, 30));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Codigo Gallina:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Cantidad de Huevos: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        txtCantidadHuevos.setEnabled(false);
        txtCantidadHuevos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadHuevosActionPerformed(evt);
            }
        });
        getContentPane().add(txtCantidadHuevos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/Imagenes/Huevos2.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, -1, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        Guardar();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        VistaMenuProducciones vista = new VistaMenuProducciones();
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtCantidadHuevosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadHuevosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadHuevosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Volver;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel tituloGranja;
    public static javax.swing.JTextField txtCantidadHuevos;
    public static javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
