/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Mockup.Ventanas;

import Gestion.VariablesGlobales;
import Modelo.Caja;
import Modelo.Direccion;
import Modelo.Granja;
import Modelo.Inventario;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class VistaGestionGranja extends javax.swing.JFrame {

    /**
     * Creates new form MInformacion
     */
    
    public boolean registrarEmpleadoInmediatamente = false;
    public boolean volverIngreso = false;
    
    public VistaGestionGranja() {
        initComponents();
        ValidarDatosGuardados();
    }
    
    public void ValidarDatosGuardados(){
        if(VariablesGlobales.granja != null){
            this.txtNombre.setText(VariablesGlobales.granja.getNombre());
            this.txtPais.setText(VariablesGlobales.granja.getDireccion().getPais());
            this.txtCiudad.setText(VariablesGlobales.granja.getDireccion().getCiudad());
            this.txtNomenclatura.setText(VariablesGlobales.granja.getDireccion().getNomenclatura());
        }
    }
    
    public void Guardar(){
        String nombre = this.txtNombre.getText();
        String pais = this.txtPais.getText();
        String ciudad = this.txtCiudad.getText();
        String nomenclatura = this.txtNomenclatura.getText();
        if(nombre.isBlank()){
            JOptionPane.showMessageDialog(null, "El campo nombre es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(pais.isBlank()){
            JOptionPane.showMessageDialog(null, "El campo pais es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(ciudad.isBlank()){
            JOptionPane.showMessageDialog(null, "El campo ciudad es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(nomenclatura.isBlank()){
            JOptionPane.showMessageDialog(null, "El campo nomenclatura es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            //ACA ESTAN TODOS LOS DATOS VALIDOS
            if(VariablesGlobales.granja == null){
                VariablesGlobales.granja = new Granja();
                VariablesGlobales.granja.setDireccion(new Direccion());
                VariablesGlobales.granja.setCaja(new Caja());
                VariablesGlobales.granja.setInventario(new Inventario());
            }
            
            VariablesGlobales.granja.setNombre(nombre);
            VariablesGlobales.granja.getDireccion().setPais(pais);
            VariablesGlobales.granja.getDireccion().setCiudad(ciudad);
            VariablesGlobales.granja.getDireccion().setNomenclatura(nomenclatura);
            
            String respuestaGuardado = VariablesGlobales.datosGranja.Guardar(VariablesGlobales.granja);
            if(respuestaGuardado.equals("OK")){
                JOptionPane.showMessageDialog(null, "Guardado exitosamente", "Exitoso", JOptionPane.INFORMATION_MESSAGE);
                //AHORA MIRAMOS SI ESTA INGRESANSO POR LA PARTE DEL LOGIN E INMEDIATAMENTE LO ENVIAMOS A GESTIONAR LA INFO DEL DUEÑO
                if(this.registrarEmpleadoInmediatamente){
                    VistaGestionDueño vista = new VistaGestionDueño();
                    vista.volverIngreso = volverIngreso;
                    vista.setVisible(true);
                    this.dispose();
                }
            }else{
                JOptionPane.showMessageDialog(null, respuestaGuardado, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    public void Volver(){
        if(this.volverIngreso){
            VariablesGlobales.vistaPrincipal.setVisible(true);
            this.dispose();
        }else{
            VistaMenuPrincipal vista = new VistaMenuPrincipal();
            vista.setVisible(true);
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        txtPais = new javax.swing.JTextField();
        Volver1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNomenclatura = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nombre de la Granja");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Ciudad");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Pais");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, 20));

        Volver.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Volver.setText("Guardar");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 140, 30));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombre.setName("txtNombre"); // NOI18N
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 290, -1));

        txtCiudad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCiudad.setName("txtCiudad"); // NOI18N
        getContentPane().add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 290, -1));

        txtPais.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPais.setName("txtPais"); // NOI18N
        getContentPane().add(txtPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 290, -1));

        Volver1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Volver1.setText("Volver");
        Volver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volver1ActionPerformed(evt);
            }
        });
        getContentPane().add(Volver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 140, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Dirección");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, 20));

        txtNomenclatura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNomenclatura.setName("txtNomenclatura"); // NOI18N
        getContentPane().add(txtNomenclatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 290, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/Imagenes/Granja.jpg"))); // NOI18N
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        Guardar();
    }//GEN-LAST:event_VolverActionPerformed

    private void Volver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volver1ActionPerformed
        Volver();
    }//GEN-LAST:event_Volver1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Volver;
    private javax.swing.JButton Volver1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNomenclatura;
    private javax.swing.JTextField txtPais;
    // End of variables declaration//GEN-END:variables
}
