/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Mockup.Ventanas;




import Gestion.CajaGestion;
import Gestion.InventarioGestion;
import Gestion.VariablesGlobales;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author angie
 */
public class VistaReporteCaja extends javax.swing.JFrame { 
    
    private CajaGestion gestion = new CajaGestion();
    ;
    
    public VistaReporteCaja() {
        initComponents();
        Mostrar(); 
    }
    public void Mostrar() {
        double totalVentaDouble = gestion.totalVentas();
        double totalIngresosDouble = gestion.totalIngresos();
        double totalEgresosDouble = gestion.totalEgresos();
        String totalVenta = String.valueOf(totalVentaDouble);
        String totalIngresos= String.valueOf(totalIngresosDouble);
        String totalEgresos= String.valueOf(totalEgresosDouble );
        Double totalCajaDouble = totalVentaDouble + totalIngresosDouble - totalEgresosDouble;
        String totalCaja= String.valueOf(totalCajaDouble );
        this.txtTotalVenta.setText(totalVenta);
        this.txtTotalIngresos.setText(totalIngresos);
        this.txtTotalEgresos.setText(totalEgresos);
        this.txtTotalCaja.setText(totalCaja);
               
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTotalVenta = new javax.swing.JTextField();
        tituloGranja = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTotalCaja = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTotalEgresos = new javax.swing.JTextField();
        txtTotalIngresos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTotalVenta.setEnabled(false);
        txtTotalVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalVentaActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotalVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 110, -1));

        tituloGranja.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tituloGranja.setText("Caja ");
        getContentPane().add(tituloGranja, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        Volver.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 130, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Total Venta: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Total Caja:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        txtTotalCaja.setEnabled(false);
        txtTotalCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalCajaActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotalCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 110, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Total Egresos:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        txtTotalEgresos.setEnabled(false);
        txtTotalEgresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalEgresosActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotalEgresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 110, -1));

        txtTotalIngresos.setEnabled(false);
        txtTotalIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalIngresosActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotalIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 110, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Total Ingresos: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/Imagenes/Huevos2.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, -1, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalVentaActionPerformed
    }//GEN-LAST:event_txtTotalVentaActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        VistaGestionCaja vista = new VistaGestionCaja();
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    private void txtTotalCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalCajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalCajaActionPerformed

    private void txtTotalEgresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalEgresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalEgresosActionPerformed

    private void txtTotalIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalIngresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalIngresosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel tituloGranja;
    public static javax.swing.JTextField txtTotalCaja;
    public static javax.swing.JTextField txtTotalEgresos;
    public static javax.swing.JTextField txtTotalIngresos;
    public static javax.swing.JTextField txtTotalVenta;
    // End of variables declaration//GEN-END:variables
}
