/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Mockup.Ventanas;

import Gestion.VariablesGlobales;
import Modelo.Caja;
import Modelo.Direccion;
import Modelo.Dueño;
import Modelo.Granja;
import Modelo.Inventario;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class VistaGestionDueño extends javax.swing.JFrame {

    /**
     * Creates new form RDueño
     */
    public boolean volverIngreso = false;
    public VistaGestionDueño() {
        initComponents();
        ValidarDatosGuardados();
    }
    
    public void ValidarDatosGuardados(){
        if(VariablesGlobales.granja.getDueño() != null){
            this.txtNombre.setText(VariablesGlobales.granja.getDueño().getNombre());
            this.txtIdentificacion.setText(VariablesGlobales.granja.getDueño().getId());
            this.txtPais.setText(VariablesGlobales.granja.getDueño().getDireccion().getPais());
            this.txtCiudad.setText(VariablesGlobales.granja.getDueño().getDireccion().getCiudad());
            this.txtNomenclatura.setText(VariablesGlobales.granja.getDueño().getDireccion().getNomenclatura());
            this.txtUsuario.setText(VariablesGlobales.granja.getDueño().getCuenta().getUsuario());
            this.txtContraseña.setText(VariablesGlobales.granja.getDueño().getCuenta().getContraseña());            
        }
    }
    
    public void Guardar(){
        String nombre = this.txtNombre.getText();
        String id = this.txtIdentificacion.getText();
        String pais = this.txtPais.getText();
        String ciudad = this.txtCiudad.getText();
        String nomenclatura = this.txtNomenclatura.getText();
        String usuario = this.txtUsuario.getText();
        String clave = this.txtContraseña.getText();
        if(nombre.isBlank()){
            JOptionPane.showMessageDialog(null, "El campo nombre es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(id.isBlank()){
            JOptionPane.showMessageDialog(null, "El identificacion pais es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(pais.isBlank()){
            JOptionPane.showMessageDialog(null, "El campo pais es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(ciudad.isBlank()){
            JOptionPane.showMessageDialog(null, "El campo ciudad es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(nomenclatura.isBlank()){
            JOptionPane.showMessageDialog(null, "El campo nomenclatura es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(usuario.isBlank()){
            JOptionPane.showMessageDialog(null, "El campo usuario es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(clave.isBlank()){
            JOptionPane.showMessageDialog(null, "El campo contraseña es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            //ACA ESTAN TODOS LOS DATOS VALIDOS
            if(VariablesGlobales.granja.getDueño() == null){
                VariablesGlobales.granja.setDueño(new Dueño());
            }
            
            VariablesGlobales.granja.getDueño().setNombre(nombre);
            VariablesGlobales.granja.getDueño().setId(id);
            VariablesGlobales.granja.getDueño().getDireccion().setPais(pais);
            VariablesGlobales.granja.getDueño().getDireccion().setCiudad(ciudad);
            VariablesGlobales.granja.getDueño().getDireccion().setNomenclatura(nomenclatura);
            VariablesGlobales.granja.getDueño().getCuenta().setUsuario(usuario);
            VariablesGlobales.granja.getDueño().getCuenta().setContraseña(clave);
            
            String respuestaGuardado = VariablesGlobales.datosDueño.Guardar(VariablesGlobales.granja.getDueño());
            if(respuestaGuardado.equals("OK")){
                JOptionPane.showMessageDialog(null, "Guardado exitosamente", "Exitoso", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, respuestaGuardado, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    public void Volver(){
        if(this.volverIngreso){
            VariablesGlobales.vistaPrincipal.setVisible(true);
            this.dispose();
        }else{
            VistaMenuPrincipal vista =new VistaMenuPrincipal();
            vista.setVisible(true);
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtIdentificacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Registrar = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNomenclatura = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        txtPais = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 170, -1));

        txtIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificacionActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 170, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Identificacion:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jLabel3.setText("Información del dueño");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("GRANJA SAN MARTIN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        Registrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Registrar.setText("Guardar");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 130, 30));

        Volver.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 130, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Ciudad:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        txtNomenclatura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNomenclatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomenclaturaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomenclatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 170, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Direccion:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Pais:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        txtCiudad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCiudadActionPerformed(evt);
            }
        });
        getContentPane().add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 170, 20));

        txtPais.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaisActionPerformed(evt);
            }
        });
        getContentPane().add(txtPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 170, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Usuario");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 170, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Contraseña");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 170, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/Imagenes/Persona2.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificacionActionPerformed
    }//GEN-LAST:event_txtIdentificacionActionPerformed

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        Guardar();
    }//GEN-LAST:event_RegistrarActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        Volver();
    }//GEN-LAST:event_VolverActionPerformed

    private void txtNomenclaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomenclaturaActionPerformed
        this.txtNomenclatura.getText();
    }//GEN-LAST:event_txtNomenclaturaActionPerformed

    private void txtCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiudadActionPerformed

    private void txtPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaisActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Registrar;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JPasswordField txtContraseña;
    public static javax.swing.JTextField txtIdentificacion;
    public static javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNomenclatura;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
