/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Mockup.Ventanas;



import Gestion.GallinaGestion;
import Gestion.InventarioGestion;
import Gestion.ProduccionGestion;
import Gestion.VariablesGlobales;
import Modelo.Gallina;
import Modelo.Produccion;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author angie
 */
public class VistaGestionInventario extends javax.swing.JFrame { 
    
    private InventarioGestion gestion = new InventarioGestion();
    ;
    
    public VistaGestionInventario() {
        initComponents();
        Mostrar(); 
    }
    public void Mostrar() {
        
               String totalHuevos = String.valueOf(gestion.totalHuevos());
               String alimentacionSuministrada= String.valueOf(gestion.totalAlimentaciones());
               this.txtTotalHuevos.setText(totalHuevos);
               this.txtTotalAlimentacionSuministrada.setText(alimentacionSuministrada);
               
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTotalHuevos = new javax.swing.JTextField();
        tituloGranja = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTotalAlimentacionSuministrada = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTotalHuevos.setEnabled(false);
        txtTotalHuevos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalHuevosActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotalHuevos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 110, -1));

        tituloGranja.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tituloGranja.setText("Inventario ");
        getContentPane().add(tituloGranja, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        Volver.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 130, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Total Huevo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Total Alimentacion Suministrada: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        txtTotalAlimentacionSuministrada.setEnabled(false);
        txtTotalAlimentacionSuministrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalAlimentacionSuministradaActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotalAlimentacionSuministrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/Imagenes/Huevos2.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, -1, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalHuevosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalHuevosActionPerformed
    }//GEN-LAST:event_txtTotalHuevosActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        VistaMenuPrincipal vista = new VistaMenuPrincipal();
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    private void txtTotalAlimentacionSuministradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalAlimentacionSuministradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalAlimentacionSuministradaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel tituloGranja;
    public static javax.swing.JTextField txtTotalAlimentacionSuministrada;
    public static javax.swing.JTextField txtTotalHuevos;
    // End of variables declaration//GEN-END:variables
}
