/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Mockup.Ventanas;

import Gestion.VariablesGlobales;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class VistaLogin extends javax.swing.JFrame {

    /**
     * Creates new form Ingreso
     */
    public VistaLogin() {
        initComponents();
    }
    
    public void ValidarAcceso(){
        if(VariablesGlobales.granja == null){
            JOptionPane.showMessageDialog(null, "No hay una granja registrada en el sistema", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(VariablesGlobales.granja.getDueño() == null){
            JOptionPane.showMessageDialog(null, "No hay un dueño registrado con acceso en el sistema", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            String usuario = txtUsuario.getText();
            String clave = txtClave.getText();
            if(usuario.isBlank()){
                JOptionPane.showMessageDialog(null, "El campo usuario es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
            }else if(clave.isBlank()){
                JOptionPane.showMessageDialog(null, "El campo contraseña es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                String usuarioReal = VariablesGlobales.granja.getDueño().getCuenta().getUsuario();
                String claveReal = VariablesGlobales.granja.getDueño().getCuenta().getContraseña();
                if(usuario.equals(usuarioReal) && clave.equals(claveReal)){
                    this.setVisible(false);
                    VistaMenuPrincipal vista = new VistaMenuPrincipal();
                    vista.setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(null, "Credenciales invalidad", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Ingresar = new javax.swing.JButton();
        txtClave = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("INICIAR SESION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Usuario :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 220, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Contraseña :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        Ingresar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Ingresar.setText("Ingresar");
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });
        getContentPane().add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 220, 30));

        txtClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveActionPerformed(evt);
            }
        });
        getContentPane().add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 220, -1));

        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setText("Registrarme");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/Imagenes/Granja.jpg"))); // NOI18N
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
        ValidarAcceso();
    }//GEN-LAST:event_IngresarActionPerformed

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveActionPerformed
    }//GEN-LAST:event_txtClaveActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        VistaGestionGranja vista = new VistaGestionGranja();
        this.setVisible(false); //OCULTAMOS ESTA VENTANA
        vista.volverIngreso = true;
        vista.registrarEmpleadoInmediatamente = true;
        vista.setVisible(true); //ABRIMOS LA VENTANA PARA GESTION DE EMPRESA
    }//GEN-LAST:event_jLabel6MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
