/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Mockup.Ventanas;

import Gestion.GallinaGestion;
import Gestion.VariablesGlobales;
import Modelo.Gallina;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class VistaGestionGallina extends javax.swing.JFrame {

    /**
     * Creates new form RDueño
     */
    public String escenario = "REGISTRAR";

    private GallinaGestion gestion = new GallinaGestion();

    public VistaGestionGallina(String escenario) {
        this.escenario = escenario;
        initComponents();
        ValidarEscenario();
    }

    public void ValidarEscenario() {
        if (this.escenario != "REGISTRAR") {
            this.txtCodigo.setEnabled(true);
            this.txtPeso.setEnabled(false);
            this.btnBuscar.setVisible(true);
            this.btnRegistrar.setEnabled(false);

        } else {
            this.btnBuscar.setVisible(false);
        }

        if (this.escenario.equals("EDITAR")) {
            btnRegistrar.setText("Actualizar");
        }

        if (this.escenario.equals("ELIMINAR")) {
            btnRegistrar.setText("Eliminar");
        }
    }

    public void Buscar() {
        String codigo = this.txtCodigo.getText();
        if (codigo.isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo de codigo es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Gallina gallina = gestion.buscar(codigo);
            if (gallina != null) {
                String peso = String.valueOf(gallina.getPeso());
                this.txtPeso.setText(peso);
                this.txtCodigo.setText(gallina.getCodigo());

                if (this.escenario.equals("EDITAR")) {

                    this.txtCodigo.setEnabled(false);
                    this.txtPeso.setEnabled(true);
                    this.btnRegistrar.setEnabled(true);
                }

                if (this.escenario.equals("ELIMINAR")) {
                    this.btnRegistrar.setEnabled(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "La Gallina no existe", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    public void Guardar() {
        try {
            String peso = this.txtPeso.getText();
            String codigo = this.txtCodigo.getText();

            if (peso.isBlank()) {
                JOptionPane.showMessageDialog(null, "El peso es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (codigo.isBlank()) {
                JOptionPane.showMessageDialog(null, "El codigo es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                Gallina gallina = new Gallina();
                double pesodouble = Double.parseDouble(peso);
                gallina.setPeso(pesodouble);
                gallina.setCodigo(codigo);

                String respuestaGuardado = "";
                if (this.escenario == "REGISTRAR") {
                    respuestaGuardado = gestion.guardar(gallina);
                }

                if (this.escenario == "EDITAR") {
                    respuestaGuardado = gestion.actualizar(codigo, gallina);
                }

                if (respuestaGuardado.equals("OK")) {
                    JOptionPane.showMessageDialog(null, "Guardado exitosamente", "Exitoso", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, respuestaGuardado, "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            //ACA PASO UN ERROR EN CONVERSIONES O CUALQUIER OTRA COSA
            JOptionPane.showMessageDialog(null, "Ocurrio un error al validar la información, porfavor verifique los datos", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }

    public void Eliminar() {
        String codigo = this.txtCodigo.getText();
        if (codigo.isBlank()) {
            JOptionPane.showMessageDialog(null, "El codigo es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String respuesta = gestion.eliminar(codigo);
            JOptionPane.showMessageDialog(null, respuesta, "Exitoso", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public void Volver() {
        VistaMenuGallinas vista = new VistaMenuGallinas();
        vista.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPeso = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tituloGranja = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoActionPerformed(evt);
            }
        });
        getContentPane().add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 170, -1));

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 170, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Codigo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Peso:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel3.setText("Información de la Gallina");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        tituloGranja.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tituloGranja.setText("GRANJA SAN MARTIN");
        getContentPane().add(tituloGranja, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrar.setText("Guardar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 130, 30));

        Volver.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 130, 30));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/Imagenes/Persona2.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
    }//GEN-LAST:event_txtPesoActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (this.escenario.equals("ELIMINAR")) {
            Eliminar();
        } else {
            Guardar();
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        Volver();
    }//GEN-LAST:event_VolverActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Volver;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel tituloGranja;
    public static javax.swing.JTextField txtCodigo;
    public static javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
