/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Mockup.Ventanas;

/**
 *
 * @author andre
 */
public class VistaMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public VistaMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        MostrarInfo = new javax.swing.JButton();
        RegisAccionistas = new javax.swing.JButton();
        RegisGallinas = new javax.swing.JButton();
        RegisProduccion = new javax.swing.JButton();
        RegistrarAlimentacion = new javax.swing.JButton();
        Inventario = new javax.swing.JButton();
        RVenta = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        RegistrarDueño = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText(" M E N U ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        MostrarInfo.setText("Información de mi granja");
        MostrarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarInfoActionPerformed(evt);
            }
        });
        getContentPane().add(MostrarInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 210, -1));

        RegisAccionistas.setText("Accionistas");
        RegisAccionistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisAccionistasActionPerformed(evt);
            }
        });
        getContentPane().add(RegisAccionistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 210, -1));

        RegisGallinas.setText("Gallinas");
        RegisGallinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisGallinasActionPerformed(evt);
            }
        });
        getContentPane().add(RegisGallinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 210, -1));

        RegisProduccion.setText("Producciones");
        RegisProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisProduccionActionPerformed(evt);
            }
        });
        getContentPane().add(RegisProduccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 210, -1));

        RegistrarAlimentacion.setText("Alimentaciones");
        RegistrarAlimentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarAlimentacionActionPerformed(evt);
            }
        });
        getContentPane().add(RegistrarAlimentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 210, -1));

        Inventario.setText("Inventario");
        Inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventarioActionPerformed(evt);
            }
        });
        getContentPane().add(Inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 210, -1));

        RVenta.setText("Caja");
        RVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RVentaActionPerformed(evt);
            }
        });
        getContentPane().add(RVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 210, -1));

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 210, -1));

        RegistrarDueño.setText("Información personal");
        RegistrarDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarDueñoActionPerformed(evt);
            }
        });
        getContentPane().add(RegistrarDueño, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 210, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/Imagenes/Granja.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void MostrarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarInfoActionPerformed
        VistaGestionGranja vista = new VistaGestionGranja();
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MostrarInfoActionPerformed

    
    private void RegisAccionistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisAccionistasActionPerformed
        VistaMenuAccionistas vista = new VistaMenuAccionistas();
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegisAccionistasActionPerformed

    
    private void RegisGallinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisGallinasActionPerformed
        VistaMenuGallinas vista = new VistaMenuGallinas();
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegisGallinasActionPerformed

    
    private void RegistrarAlimentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarAlimentacionActionPerformed
        VistaMenuAlimentaciones vista = new VistaMenuAlimentaciones();
        vista.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_RegistrarAlimentacionActionPerformed

    
    private void RegisProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisProduccionActionPerformed
        VistaMenuProducciones vista = new VistaMenuProducciones();
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegisProduccionActionPerformed

    
    private void InventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioActionPerformed
        VistaGestionInventario vista = new VistaGestionInventario();
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InventarioActionPerformed

    
    
    private void RVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RVentaActionPerformed
        VistaGestionCaja vista = new VistaGestionCaja();
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RVentaActionPerformed

    
    
    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    
    private void RegistrarDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarDueñoActionPerformed
        VistaGestionDueño vista = new VistaGestionDueño();
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegistrarDueñoActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Inventario;
    private javax.swing.JButton MostrarInfo;
    private javax.swing.JButton RVenta;
    private javax.swing.JButton RegisAccionistas;
    private javax.swing.JButton RegisGallinas;
    private javax.swing.JButton RegisProduccion;
    private javax.swing.JButton RegistrarAlimentacion;
    private javax.swing.JButton RegistrarDueño;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
